name: Build and Test Website

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Runs on the latest Ubuntu environment

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2  # Checkout the code from the repository

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Set the Node.js version (or adjust as needed)

      - name: Install Dependencies
        run: |
          npm install  # Or `yarn install` if you use Yarn

      - name: Build Website
        run: |
          npm run build  # Build command for your project (e.g., for React, Vue, etc.)

      - name: Run Tests
        run: |
          npm test  # Or any test command for your project
